apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-admins
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 3
      template:
        spec:
          containers:
          - env:
            - name: CLUSTERFUZZ_RELEASE
              value: {{ quote .Values.yncAdmins.syncAdmins.env.clusterfuzzRelease
                }}
            - name: RUN_CMD
              value: {{ quote .Values.yncAdmins.syncAdmins.env.runCmd }}
            - name: IS_K8S_ENV
              value: {{ quote .Values.yncAdmins.syncAdmins.env.isK8SEnv }}
            - name: DISABLE_MOUNTS
              value: {{ quote .Values.yncAdmins.syncAdmins.env.disableMounts }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            image: {{ .Values.yncAdmins.syncAdmins.image.repository }}:{{ .Values.yncAdmins.syncAdmins.image.tag
              | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.yncAdmins.syncAdmins.imagePullPolicy }}
            name: sync-admins
            resources: {}
          restartPolicy: OnFailure
  schedule: {{ .Values.yncAdmins.schedule | quote }}
