# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- name: python:3.11
  entrypoint: bash
  args:
  - -c
  - |
    butler.py package --platform=all
    mkdir /workspace/zips
    cp -r deployment/* /workspace/zips/.
- name: ubuntu
  entrypoint: bash
  args:
  - -c
  - ls
  dir: '/workspace/zips'

timeout: 14400s
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: 500
  logging: CLOUD_LOGGING_ONLY
